const CONFIG = {
    titleWeb: "Maraqlı bir sual",
    introTitle: 'İllərdir görüşmədiyimizi nəzərə alaraq',
    introDesc: `belə düşünürəm ki bunu dəvam etdirmək ikimizə də zülm olar`,
    btnIntro: 'Bura bas yavrim',
    title: 'Ona görə dəəəəə',
    desc: 'Bu altıncı gün kinoya baxmağa nə diyərsən?',
    btnYes: 'Əlllləbdə ki, haçan istəsən',
    btnNo: 'yx',
    question: 'İstəyicəyini bilirdimmm',
    btnReply: 'İndi isə bura fikir vermədən TG da mənə nə giyinəcəyini ee yəni nəyə baxacağımızı di',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối nay 7h, mình qua đón đi chơi nha.',
    btnAccept: 'Okiiiii lun <3',
    }
