const CONFIG = {
    titleWeb: "Maraqlı bir sual",
    introTitle: 'İllərdir görüşmədiyimizi nəzərə alaraq',
    introDesc: `Belə düşünürəm ki, bunu dəvam etdirmək ikimizə də zülm olar`,
    btnIntro: 'Bura bas yavrim',
    title: 'Ona görə dəəəəə',
    desc: 'Bu altıncı gün kinoya baxmağa nə diyərsən?',
    btnYes: 'Əlllbətdə ki, haçan istəsənnn',
    btnNo: 'yx',
    question: 'İstəyicəyini bilirdimmm, nə giyinəcəksən?',
    btnReply: 'Bura da bas htym',
    reply: 'Sən nə giyinməmi istəsən hytm',
    mess: 'Nə istəsəm? ou nə qədər də cooomərtsən hytm 😘😘',
    messDesc: '6 cı gün kinoda görüşərik onda',
    btnAccept: 'Mənə bir haqq vermək üçün bura bas',
    }
